### PR TITLE
Fix msg attribute size calcs, include data type attr

### PR DESCRIPTION
**Pull request by malimohub**
Looks like we should be taking into account additional message attributes as apart of message size derivation. See Java lib takes into account DataType 
[https://github.com/awslabs/amazon-sqs-java-extended-client-lib/blob/master/src/mai[…]/java/com/amazon/sqs/javamessaging/AmazonSQSExtendedClient.java](https://github.com/awslabs/amazon-sqs-java-extended-client-lib/blob/master/src/main/java/com/amazon/sqs/javamessaging/AmazonSQSExtendedClient.java#L939)

This PR should address that.

Wondering if we  also need to include the following in msg attribute calculations, which are also seen on the types.MessageAttributeValue object
- BinaryListValues
- StringListValues

Screenshot 2024-03-04 at 4 03 23 PM

### CODE REVIEW

**Review by edalorzo — APPROVED** [review]
LGTM

**Comment by co-go** [comment]
This is awesome! I must have missed this the first time around when calculating the size of message attributes. 

As for the "List" fields. Given they're left unimplemented right now, I would prefer to hold off on bringing those into the message size calculation. If/when they ever become fully integrated with the AWS SQS client, we can always add in that change then.

Lastly, I added in some integration tests last week, which use my AWS credentials with the extended client to run through some scenarios. That stage seems to be failing on your PR because it's a fork (instead of a branch). I'll try to tinker with it a bit more to get those tests running properly here.

**Review by co-go — APPROVED** [review]

**Comment by malimohub** [comment]
@co-go sounds good, wanna merge this guy in ?

**Review by co-go — APPROVED** [review]

**Comment by co-go** [comment]
@malimohub Thanks for your patience as I was sorting out the integration tests for public forks! I'll be able to run them much more quickly moving forward now. Merged!

**Pull request merged**
